version: '3.4'

networks:
  deploy-guide:
    driver: bridge

services:
  weather:
    image: weather
    container_name: weather
    build:
      context: .
      dockerfile: WeatherWebsite/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - deploy-guide
    depends_on:
      - postgres
    command: ["dotnet", "ef", "database update"]

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - deploy-guide
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: